package Frame.Proffesor;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Logic.*;
import Server.Server;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author 1
 */
public class changeLesson extends javax.swing.JFrame {

    /**
     * Creates new form changeLesson
     */
    public changeLesson(Professor professor) {
        this.professor = professor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        actionName = new javax.swing.JLabel();
        TA = new javax.swing.JTextField();
        text = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        prerequisite = new javax.swing.JTextField();
        done = new javax.swing.JButton();
        text2 = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        Professor2 = new javax.swing.JTextField();
        text4 = new javax.swing.JLabel();
        text5 = new javax.swing.JLabel();
        text6 = new javax.swing.JLabel();
        text7 = new javax.swing.JLabel();
        text8 = new javax.swing.JLabel();
        text9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        requiredFor = new javax.swing.JTextField();
        grade = new javax.swing.JTextField();
        capacity = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        name = new javax.swing.JTextField();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        actionName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(actionName);
        actionName.setBounds(0, 90, 180, 40);

        TA.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(TA);
        TA.setBounds(0, 300, 120, 20);

        text.setText("Enter the name of the TA(s) :");
        jPanel1.add(text);
        text.setBounds(0, 270, 190, 20);

        text1.setText("Enter the name of the prerequisite(s) :");
        jPanel1.add(text1);
        text1.setBounds(0, 390, 200, 20);

        prerequisite.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(prerequisite);
        prerequisite.setBounds(0, 420, 120, 20);


        text2.setText("Enter code of the course :");
        jPanel1.add(text2);
        text2.setBounds(0, 330, 190, 20);

        text3.setText("Enter the name of the professor(s) :");
        jPanel1.add(text3);
        text3.setBounds(0, 210, 190, 20);

        code.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(code);
        code.setBounds(0, 360, 120, 20);

        Professor2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Professor2);
        Professor2.setBounds(0, 240, 120, 20);

        text4.setText("Enter the name of the course(s) this lesoon is required for :");
        jPanel1.add(text4);
        text4.setBounds(210, 150, 350, 20);

        text5.setText("Enter the grade :");
        jPanel1.add(text5);
        text5.setBounds(210, 210, 170, 20);

        text6.setText("Enter the name of the course :");
        jPanel1.add(text6);
        text6.setBounds(210, 270, 170, 20);

        text7.setText("Enter the time of the class :");
        jPanel1.add(text7);
        text7.setBounds(210, 330, 170, 20);

        text8.setText("Enter the date of final exam :");
        jPanel1.add(text8);
        text8.setBounds(210, 390, 170, 20);

        text9.setText("Enter capasity of course :");
        jPanel1.add(text9);
        text9.setBounds(0, 150, 170, 20);

        requiredFor.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(requiredFor);
        requiredFor.setBounds(210, 180, 120, 20);

        grade.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(grade);
        grade.setBounds(210, 240, 120, 20);

        capacity.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(capacity);
        capacity.setBounds(210, 300, 120, 20);

        time.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(time);
        time.setBounds(210, 360, 120, 20);

        date.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(date);
        date.setBounds(210, 420, 120, 20);

        name.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(name);
        name.setBounds(0, 180, 120, 20);


        jButton5.setBackground(new java.awt.Color(255, 179, 200));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(490, 20, 20, 20);

        jButton6.setBackground(new java.awt.Color(153, 232, 173));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(460, 20, 20, 20);

        jButton7.setBackground(new java.awt.Color(149, 126, 184));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(430, 20, 20, 20);

        jButton8.setBackground(new java.awt.Color(237, 197, 28));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(400, 20, 20, 20);

        jButton9.setBackground(new java.awt.Color(255, 148, 144));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(520, 20, 20, 20);

        jLabel1.setFont(new java.awt.Font("Doulos SIL", 3, 24)); // NOI18N
        jLabel1.setText("EDU Sharif");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 140, 38);

        jLabel2.setText("Email :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 470, 270, 16);

        jLabel3.setText("Last Entry : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(327, 60, 210, 16);

        jLabel4.setText("Time :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 90, 210, 16);

        exit.setBackground(new java.awt.Color(204, 204, 204));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(470, 460, 72, 22);

        done.setBackground(new java.awt.Color(204, 204, 204));
        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        jPanel1.add(done);
        done.setBounds(470, 230, 80, 30);



        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(237,197,28));
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(149,126,184));
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(153,232,173));
    }
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(255,179,200));
    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(255,148,144));
    }
    private void doneActionPerformed(java.awt.event.ActionEvent evt) {
        switch (actionName.getText()){
            case "Change course":
               for(Lesson l : Server.getLessons()){
                   if (l.getName().equals(name.getText())) {
                       l.getProfessors().add(Professor2.getText());
                       l.getTAs().add(TA.getText());
                       l.setCode(Integer.valueOf(code.getText()));
                       l.getPrerequisite().add(prerequisite.getText());
                       l.getRequiredFor().add(requiredFor.getText());
                       l.setType(studentType.valueOf(grade.getText()));
                       l.setCapacity(Integer.valueOf(capacity.getText()));
                       l.setTimeClass(time.getText());
                       l.setExamDate(date.getText());
                       break;
                   }
               }
                break;
            case "Delete course":
                for(Lesson l : Server.getLessons()){
                    if (l.getName().equals(name.getText())) {
                        Server.getLessons().remove(l);
                        break;
                    }
                }
                break;
            case "Add course":
                Lesson l = new Lesson();
                l.setType(studentType.valueOf(grade.getText()));
                l.setCapacity(Integer.valueOf(capacity.getText()));
                l.setTimeClass(time.getText());
                l.setExamDate(date.getText());
                l.setName(name.getText());
                l.getProfessors().add(Professor2.getText());
                l.getTAs().add(TA.getText());
                l.setCode(Integer.valueOf(code.getText()));
                l.getPrerequisite().add(prerequisite.getText());
                l.getRequiredFor().add(requiredFor.getText());
                Server.getLessons().add(l);
                //Server.writeCourse(l);
                break;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changeLesson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changeLesson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changeLesson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changeLesson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changeLesson(new Professor()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField Professor2;
    private javax.swing.JTextField TA;
    private javax.swing.JLabel actionName;
    private javax.swing.JButton done;
    private javax.swing.JTextField code;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField prerequisite;
    private javax.swing.JTextField requiredFor;
    private javax.swing.JTextField grade;
    private javax.swing.JTextField capacity;
    private javax.swing.JTextField time;
    private javax.swing.JTextField date;
    private javax.swing.JTextField name;
    private javax.swing.JLabel text;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel text4;
    private javax.swing.JLabel text5;
    private javax.swing.JLabel text6;
    private javax.swing.JLabel text7;
    private javax.swing.JLabel text8;
    private javax.swing.JLabel text9;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private Professor professor;
    // End of variables declaration


    public JLabel getActionName() {
        return actionName;
    }

    public void setActionName(JLabel actionName) {
        this.actionName = actionName;
    }
}


