package Frame.Proffesor;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Logic.Professor;
import Logic.User;
import Logic.professorType;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @Rabee
 */
public class mainProfessor extends javax.swing.JFrame {

    /**
     * Creates new form mainProfessor
     */
    public mainProfessor(Professor professor) {
        this.professor = professor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        message = new javax.swing.JButton();
        messenger = new javax.swing.JButton();

        jButton11.setVisible(false);
        jButton12.setVisible(false);
        jButton13.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Sign up matters");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 80, 140, 22);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Educational Services");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 160, 140, 22);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setText("Students and Grades");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(0, 230, 140, 22);

        message.setIcon(new ImageIcon("D:/finalEDU/src/Images/bell.png"));
        jPanel1.add(message);
        message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageActionPerformed(evt);
            }
        });
        message.setBounds(408, 470, 21, 22);

        messenger.setIcon(new ImageIcon("D:/finalEDU/src/Images/messageIcon.png"));
        jPanel1.add(messenger);
        messenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messengerActionPerformed(evt);
            }
        });
        messenger.setBounds(429, 470, 21, 22);


        jButton13.setBackground(new java.awt.Color(204, 204, 204));
        jButton13.setText("Temporary Marks");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(140, 230, 140, 11);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setText("User Profile");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(0, 310, 140, 22);

        jButton44.setBackground(new java.awt.Color(204, 204, 204));
        jButton44.setText("new user");
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton44);
        jButton44.setBounds(0, 390, 140, 22);
        if (professor.getTypeP() != professorType.Deputy) {
            jButton44.setVisible(false);
        }

        jButton5.setBackground(new java.awt.Color(255, 179, 200));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(490, 20, 20, 20);

        jButton6.setBackground(new java.awt.Color(153, 232, 173));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(460, 20, 20, 20);

        jButton7.setBackground(new java.awt.Color(149, 126, 184));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(430, 20, 20, 20);

        jButton8.setBackground(new java.awt.Color(237, 197, 28));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(400, 20, 20, 20);

        jButton9.setBackground(new java.awt.Color(255, 148, 144));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(520, 20, 20, 20);

        jLabel1.setFont(new java.awt.Font("Doulos SIL", 3, 24)); // NOI18N
        jLabel1.setText("EDU Sharif");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 140, 38);

        jLabel2.setText("Email :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 470, 270, 16);

        jLabel3.setText("Last Entry : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(327, 60, 210, 16);


        jPanel1.add(Time);
        Time.setBounds(350, 90, 210, 16);

        jPanel1.add(date);
        date.setBounds(350, 110, 210, 16);

        dt();
        times();


        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setText("Exit");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(470, 460, 72, 22);

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setText("Professors");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(140, 60, 90, 22);

        jButton12.setBackground(new java.awt.Color(204, 204, 204));
        jButton12.setText("Lessons");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(140, 100, 90, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );
        this.setSize(600, 500);

        pack();
    }// </editor-fold>

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(237, 197, 28));
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(149, 126, 184));
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(153, 232, 173));
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(255, 179, 200));
    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(255, 148, 144));
    }
    private void messageActionPerformed(java.awt.event.ActionEvent evt) {

    }
    private void messengerActionPerformed(java.awt.event.ActionEvent evt) {

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        jButton11.setVisible(true);
        jButton12.setVisible(true);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        new ProfessorsList(professor).setVisible(true);


    }

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        new lessonsList(professor).setVisible(true);

    }

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        new temporaryMarks(professor).setVisible(true);

    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Professor professor = new Professor();
                new mainProfessor(professor).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton message;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton messenger;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel date;
    private javax.swing.JPanel jPanel1;
    private Professor professor;

    // End of variables declaration
    public void dt() {
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MMM-dd");
        String dd = sdf.format(d);
        date.setText(dd);

    }

    // time
    Timer t;
    SimpleDateFormat st;

    public void times() {

        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                Date dt = new Date();
                st = new SimpleDateFormat("hh:mm:ss");
                String tt = st.format(dt);
                Time.setText(tt);
            }
        });
    }
}

   