package Frame.Proffesor;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Logic.User;

import java.awt.*;

/**
 *
 * @Rabee
 */
public class ProfessorsList extends javax.swing.JFrame {


    public ProfessorsList(User user) {
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(null);

        jLabel3.setText("Last Entry : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(327, 60, 210, 16);

        jLabel4.setText("Time :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 90, 210, 16);

        jButton8.setBackground(new java.awt.Color(237, 197, 28));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(400, 20, 20, 20);

        jButton7.setBackground(new java.awt.Color(149, 126, 184));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(430, 20, 20, 20);

        jButton6.setBackground(new java.awt.Color(153, 232, 173));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(460, 20, 20, 20);

        jButton5.setBackground(new java.awt.Color(255, 179, 200));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(490, 20, 20, 20);

        jButton9.setBackground(new java.awt.Color(255, 148, 144));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(520, 20, 20, 20);

        jLabel1.setText("Email :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 430, 210, 16);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Exit");
        jPanel1.add(jButton1);
        jButton1.setBounds(470, 430, 72, 22);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Name");
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 100, 90, 22);

        jLabel2.setFont(new java.awt.Font("Doulos SIL", 3, 24)); // NOI18N
        jLabel2.setText("EDU Sharif");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 140, 38);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 120, 310, 310);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setText("Rank");
        jPanel1.add(jButton3);
        jButton3.setBounds(110, 100, 90, 22);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setText("College");
        jPanel1.add(jButton4);
        jButton4.setBounds(220, 100, 90, 22);

        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setText("Home");
        jPanel1.add(jButton10);
        jButton10.setBounds(380, 430, 72, 22);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(0, 70, 90, 22);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(110, 70, 90, 22);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(220, 70, 90, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        this.setSize(600,500);
        this.setResizable(false);
        pack();
    }// </editor-fold>

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(237,197,28));
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(149,126,184));
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(153,232,173));
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(255,179,200));
    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(255,148,144));
    }


    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                User user = new User();
                new ProfessorsList(user).setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private User user;
    // End of variables declaration
}
