package Frame.Proffesor;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Logic.User;

import java.awt.*;

/**
 *
 * @author 1
 */
public class temporaryMarks extends javax.swing.JFrame {

    /**
     * Creates new form temporaryMarks
     */
    public temporaryMarks(User user) {
        initComponents();
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 3, 18)); // NOI18N
        jLabel1.setText("EDU SHARIF");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 150, 70);

        jLabel2.setText("Last Entry : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(360, 60, 240, 16);

        jLabel3.setText("Time:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(360, 80, 160, 30);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 10, 60, 70);

        jLabel5.setText("Email : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 480, 290, 16);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(430, 470, 75, 22);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(520, 470, 72, 22);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 340, 350);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(450, 150, 70, 22);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(450, 200, 20, 22);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(450, 250, 70, 22);

        jLabel6.setText("Student Code:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 150, 90, 20);

        jLabel7.setText("Mark : ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(350, 200, 90, 20);
        jLabel7.setVisible(false);

        jLabel8.setText("Response : ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(350, 250, 80, 30);
        jLabel8.setVisible(false);

        jButton3.setText("Temporary");
        jPanel1.add(jButton3);
        jButton3.setBounds(480, 190, 90, 22);
        jPanel1.add(jButton4);
        jButton4.setBounds(530, 250, 20, 20);
        jPanel1.add(jButton5);
        jButton5.setBounds(530, 150, 20, 20);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Final");
        jPanel1.add(jButton6);
        jButton6.setBounds(480, 210, 90, 22);
        jButton3.setVisible(false);
        jButton6.setVisible(false);
        jButton4.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);

        jButton55.setBackground(new java.awt.Color(255, 179, 200));
        jButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton55ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton55);
        jButton55.setBounds(490, 20, 20, 20);

        jButton66.setBackground(new java.awt.Color(153, 232, 173));
        jButton66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton66ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton66);
        jButton66.setBounds(460, 20, 20, 20);

        jButton77.setBackground(new java.awt.Color(149, 126, 184));
        jButton77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton77ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton77);
        jButton77.setBounds(430, 20, 20, 20);

        jButton88.setBackground(new java.awt.Color(237, 197, 28));
        jButton88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton88ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton88);
        jButton88.setBounds(400, 20, 20, 20);

        jButton99.setBackground(new java.awt.Color(255, 148, 144));
        jButton99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton99ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton99);
        jButton99.setBounds(520, 20, 20, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        this.setSize(600,500);
        this.setResizable(false);
        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(temporaryMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(temporaryMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(temporaryMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(temporaryMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                User user = new User();
                new temporaryMarks(user).setVisible(true);
            }
        });
    }
    private void jButton88ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(237,197,28));
    }

    private void jButton77ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(149,126,184));
    }

    private void jButton66ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(153,232,173));
    }

    private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(255,179,200));
    }

    private void jButton99ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(255,148,144));
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        jButton3.setVisible(true);
        jButton6.setVisible(true);
        jButton4.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jLabel8.setVisible(true);
        jLabel7.setVisible(true);
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton99;
    private User user;
    // End of variables declaration
}