package CW;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Logic.Lesson;
import Logic.Student;
import Logic.Student;
import Server.Server;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author 1
 */
public class mainCwS extends javax.swing.JFrame {
    private Student Student;
    /**
     * Creates new form mainCwS
     */
    public mainCwS(Student Student) {
        this.Student = Student;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        cw = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        picture = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        Enter = new javax.swing.JButton();
        exit1 = new javax.swing.JButton();
        time1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        courses = new javax.swing.JTextArea();
        lessonCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        messages1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(null);

        back.setBackground(new java.awt.Color(255, 204, 255));
        back.setText("Back");
        jPanel1.add(back);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        back.setBounds(70, 450, 60, 22);

        cw.setBackground(new java.awt.Color(255, 204, 255));
        cw.setFont(new java.awt.Font("French Script MT", 3, 48)); // NOI18N
        cw.setForeground(new java.awt.Color(255, 204, 255));
        cw.setText("CW SHARIF");
        jPanel1.add(cw);
        cw.setBounds(0, 0, 290, 80);

        name.setBackground(new java.awt.Color(255, 204, 255));
        name.setFont(new java.awt.Font("French Script MT", 2, 14)); // NOI18N
        name.setOpaque(true);
        name.setText(Student.getName());
        jPanel1.add(name);
        name.setBounds(410, 10, 100, 20);
        jPanel1.add(picture);
        picture.setBounds(370, 0, 30, 50);

        time.setBackground(new java.awt.Color(255, 204, 255));
        time.setOpaque(true);
        jPanel1.add(time);
        time.setBounds(370, 400, 180, 30);

        Enter.setBackground(new java.awt.Color(255, 204, 255));
        Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterActionPerformed(evt);
            }
        });
        jPanel1.add(Enter);
        Enter.setBounds(530, 150, 20, 22);

        exit1.setBackground(new java.awt.Color(255, 204, 255));
        exit1.setText("Exit");
        jPanel1.add(exit1);
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });

        exit1.setBounds(10, 450, 50, 22);

        time1.setBackground(new java.awt.Color(255, 204, 255));
        time1.setOpaque(true);
        jPanel1.add(time1);
        time1.setBounds(370, 440, 180, 30);
        dt();
        times();

        courses.setColumns(20);
        courses.setRows(5);
        jScrollPane1.setViewportView(courses);
        int i = 0;
        for(String s : Student.getMyLessons().keySet()){
            if (i==0){
                courses.setText(courses.getText()+ Student.getMyLessons().get(s)+" by "+s);
            }else {
                courses.setText(courses.getText() + Student.getMyLessons().get(s)+" by "+s);
            }
            i++;
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 270, 300);
        jPanel1.add(lessonCode);
        lessonCode.setBounds(420, 150, 100, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 255));
        jLabel1.setText("Enter Course Name :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 150, 130, 20);

        messages1.setBackground(new java.awt.Color(255, 204, 255));
        messages1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messages1ActionPerformed(evt);
            }
        });
        jPanel1.add(messages1);
        messages1.setBounds(520, 10, 20, 22);

        jLabel2.setFont(new java.awt.Font("Freestyle Script", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 255));
        jLabel2.setText("Courses");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 70, 220, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void EnterActionPerformed(java.awt.event.ActionEvent evt) {
        for (Lesson l : Server.getLessons()){
            if (l.getName().equals(lessonCode.getText())){
                dispose();
                //new stdentCourse(l).setVisible(true);
            }
        }
    }

    private void messages1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainCwS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainCwS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainCwS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainCwS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainCwS(new Student()).setVisible(true);
            }
        });
    }

    private void backActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        new loginCw().setVisible(true);
    }

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }



    // Variables declaration - do not modify                     
    private javax.swing.JButton Enter;
    private javax.swing.JButton back;
    private javax.swing.JTextArea courses;
    private javax.swing.JLabel cw;
    private javax.swing.JButton exit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lessonCode;
    private javax.swing.JButton messages1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel picture;
    private javax.swing.JLabel time;
    private javax.swing.JLabel time1;
    // End of variables declaration

    public void dt(){
        Date d  =new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MMM-dd");
        String dd = sdf.format(d);
        time.setText(dd);
    }
    // time
    Timer t ;
    SimpleDateFormat st ;
    public void times(){

        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                Date dt  =new Date();
                st = new SimpleDateFormat("hh:mm:ss");
                String tt = st.format(dt);
                time1.setText(tt);
            }
        });
        t.start();

    }
}
