package CW;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Logic.Lesson;
import Logic.Professor;

/**
 *
 * @author 1
 */
public class professorCourse extends javax.swing.JFrame {

    /**
     * Creates new form professorCourse
     */
    private Lesson lesson;
    private Professor professor;
    public professorCourse(Lesson lesson, Professor professor) {
        this.lesson = lesson;
        this.professor = professor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        choose = new javax.swing.JButton();
        cw = new javax.swing.JLabel();
        nameOfCourse = new javax.swing.JLabel();
        picture = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        exit1 = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        studentNum = new javax.swing.JTextField();
        messages1 = new javax.swing.JButton();
        assistant = new javax.swing.JRadioButton();
        normal = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        posts = new javax.swing.JButton();
        newPost1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setLayout(null);

        choose.setBackground(new java.awt.Color(204, 51, 0));
        choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseActionPerformed(evt);
            }
        });
        jPanel1.add(choose);
        choose.setBounds(540, 110, 20, 22);

        cw.setBackground(new java.awt.Color(255, 204, 255));
        cw.setFont(new java.awt.Font("French Script MT", 3, 48)); // NOI18N
        cw.setText("CW SHARIF");
        jPanel1.add(cw);
        cw.setBounds(0, 0, 290, 80);

        nameOfCourse.setBackground(new java.awt.Color(204, 51, 0));
        nameOfCourse.setFont(new java.awt.Font("French Script MT", 2, 14)); // NOI18N
        nameOfCourse.setOpaque(true);
        jPanel1.add(nameOfCourse);
        nameOfCourse.setBounds(410, 40, 100, 20);
        jPanel1.add(picture);
        picture.setBounds(370, 0, 30, 50);

        back.setBackground(new java.awt.Color(204, 51, 0));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(70, 450, 60, 22);

        exit1.setBackground(new java.awt.Color(204, 51, 0));
        exit1.setText("Exit");
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });
        jPanel1.add(exit1);
        exit1.setBounds(10, 450, 50, 22);

        time.setBackground(new java.awt.Color(204, 51, 0));
        time.setOpaque(true);
        jPanel1.add(time);
        time.setBounds(400, 440, 150, 30);

        jLabel1.setText("Add student to this course : (enter student's number)");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 110, 300, 16);

        name1.setBackground(new java.awt.Color(204, 51, 0));
        name1.setFont(new java.awt.Font("French Script MT", 2, 14)); // NOI18N
        name1.setOpaque(true);
        jPanel1.add(name1);
        name1.setBounds(410, 10, 100, 20);

        studentNum.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.add(studentNum);
        studentNum.setBounds(290, 110, 240, 22);

        messages1.setBackground(new java.awt.Color(204, 51, 0));
        messages1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messages1ActionPerformed(evt);
            }
        });
        jPanel1.add(messages1);
        messages1.setBounds(520, 10, 20, 22);

        assistant.setText("Assistant");
        assistant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assistantActionPerformed(evt);
            }
        });
        jPanel1.add(assistant);
        assistant.setBounds(290, 150, 98, 20);

        normal.setText("Normal");
        normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalActionPerformed(evt);
            }
        });
        jPanel1.add(normal);
        normal.setBounds(400, 150, 63, 20);

        jTextArea1.setBackground(new java.awt.Color(255, 204, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(400, 200, 150, 230);

        jLabel2.setText("List of assistants : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(420, 180, 160, 16);

        posts.setBackground(new java.awt.Color(255, 204, 0));
        posts.setText("see all posts");
        posts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postsActionPerformed(evt);
            }
        });
        jPanel1.add(posts);
        posts.setBounds(0, 280, 150, 22);

        newPost1.setBackground(new java.awt.Color(255, 204, 0));
        newPost1.setText("making new post");
        newPost1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPost1ActionPerformed(evt);
            }
        });
        jPanel1.add(newPost1);
        newPost1.setBounds(0, 250, 150, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void chooseActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void messages1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void assistantActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void normalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void backActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void postsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void newPost1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(professorCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(professorCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(professorCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(professorCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new professorCourse(new Lesson(),new Professor()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JRadioButton assistant;
    private javax.swing.JButton back;
    private javax.swing.JButton choose;
    private javax.swing.JLabel cw;
    private javax.swing.JButton exit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton messages1;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel nameOfCourse;
    private javax.swing.JButton newPost1;
    private javax.swing.JRadioButton normal;
    private javax.swing.JLabel picture;
    private javax.swing.JButton posts;
    private javax.swing.JTextField studentNum;
    private javax.swing.JLabel time;
    // End of variables declaration
}
