package Frame.General;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Frame.Proffesor.mainProfessor;
import Frame.Student.mainStudent;
import Logic.Professor;
import Logic.Student;
import Server.Server;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;

/**
 *
 * @author Rabee
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        generateCaptcha();
        jPanel1.setLayout(null);

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(70, 70, 140, 22);

        name.setText("EDU");
        name.setFont(new java.awt.Font("Doulos SIL", 3, 40));
        name.setBounds(70, 30, 140, 40);
        jPanel1.add(name);

        jLabel1.setText("Password :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 120, 80, 20);

        jLabel2.setText("Username :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 70, 80, 20);

        jPasswordField2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(70, 120, 140, 22);

        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 160, 100, 40);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Login");
        jPanel1.add(jButton1);
        jButton1.setBounds(100, 270, 72, 22);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(70, 200, 140, 22);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jButton2);
        jButton2.setBounds(210, 200, 22, 22);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        this.setSize(300, 400);

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        boolean exist = false;
        if (jTextField3.getText().equals(captcha + "")) {
            for (Student s : Server.getStudents()) {
                if (s.getUsername().equals(jTextField1.getText()) && s.getPassword().equals(jPasswordField2.getText())) {
                    this.dispose();
                    new mainStudent(s).setVisible(true);
                    s.setLastEntry(dd + " " + tt);
                    //Server.changeS(s);
                    exist = true;
                    break;
                }
            }
            for (Professor s : Server.getProfessors()) {
                if (s.getUsername().equals(jTextField1.getText()) && s.getPassword().equals(jPasswordField2.getText())) {
                    this.dispose();
                    new mainProfessor(s).setVisible(true);
                    s.setLastEntry(dd + " " + tt);
                    //Server.changeP(s);
                    exist = true;
                    break;
                }
            }
        }
        if (!exist) {
            jLabel3.setVisible(true);
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        generateCaptcha();
    }


    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel name;
    //captcha label
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField3;
    private int captcha;
    private ArrayList<ImageIcon> images = new ArrayList<>();
    // End of variables declaration

    private void generateCaptcha() {
        images.add(new ImageIcon("D:/myedu3/src/Images/jcaptcha.jpg"));
        images.add(new ImageIcon("D:/myedu3/src/Images/jcaptcha (1).jpg"));
        images.add(new ImageIcon("D:/myedu3/src/Images/jcaptcha (2).jpg"));
        images.add(new ImageIcon("D:/myedu3/src/Images/jcaptcha (3).jpg"));
        images.add(new ImageIcon("D:/myedu3/src/Images/jcaptcha (4).jpg"));

        Random rand = new Random();
        int i = rand.nextInt(4);
        System.out.println(i);
        jLabel3.setIcon(images.get(i));
        switch (i) {
            case 0:
                captcha = 2728;
                break;
            case 1:
                captcha = 4908;
                break;
            case 2:
                captcha = 8763;
                break;
            case 3:
                captcha = 7864;
                break;
            case 4:
                captcha = 7621;
                break;
        }
    }

    String dd;

    public void dt() {
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MMM-dd");
        dd = sdf.format(d);

    }

    // time
    Timer t;
    SimpleDateFormat st;
    String tt;

    public void times() {

        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                Date dt = new Date();
                st = new SimpleDateFormat("hh:mm:ss");
                tt = st.format(dt);

            }
        });
        t.start();
    }
}

    