package Frame.General;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Logic.Professor;
import Logic.Student;
import Logic.User;
import Server.Server;

/**
 *
 * @author 1
 */
public class messenger extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form messenger
     */
    public messenger() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messages = new javax.swing.JTextArea();
        send = new javax.swing.JButton();
        receiverName = new javax.swing.JLabel();
        Professor = new javax.swing.JRadioButton();
        student = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        error = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        messageToSend = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        userList = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(null);

        messages.setBackground(new java.awt.Color(0, 102, 0));
        messages.setColumns(20);
        messages.setForeground(new java.awt.Color(204, 255, 204));
        messages.setRows(5);
        jScrollPane1.setViewportView(messages);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(190, 10, 250, 260);

        send.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(send);
        send.setBounds(410, 280, 30, 30);

        receiverName.setBackground(new java.awt.Color(153, 255, 153));
        receiverName.setOpaque(true);
        jPanel1.add(receiverName);
        if (receiver!=null) {
            receiverName.setText(receiver.getName());
        }

        receiverName.setBounds(230, 330, 170, 20);

        Professor.setText("Professor");
        jPanel1.add(Professor);
        Professor.setBounds(0, 60, 80, 20);

        student.setText("Student");
        jPanel1.add(student);
        student.setBounds(0, 90, 64, 20);

        jLabel1.setText("Search For messages :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 20, 120, 16);
        jPanel1.add(userName);
        userName.setBounds(0, 120, 110, 22);
        jPanel1.add(error);
        error.setBounds(10, 150, 110, 20);

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 120, 20, 20);
        jPanel1.add(messageToSend);
        messageToSend.setBounds(210, 280, 200, 30);

        userList.setColumns(20);
        userList.setRows(5);
        jScrollPane2.setViewportView(userList);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 160, 150, 260);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new messenger().setVisible(true);
            }
        });
    }
    private void ProfessorActionPerformed(java.awt.event.ActionEvent evt) {
        type = "P";
        int  i = 1;
        for (Logic.Professor p : Server.getProfessors()){
            if (i==1) {
                userList.setText(i + "- " + p.getName());
            }else {
                userList.setText("\n"+i + "- " + p.getName());
            }
            i++;
        }
    }

    private void studentActionPerformed(java.awt.event.ActionEvent evt) {
        type = "S";
        int i = 1;
        for (Student p : Server.getStudents()) {
            if (i == 1) {
                userList.setText(i + "- " + p.getName());
            } else {
                userList.setText("\n" + i + "- " + p.getName());
            }
            i++;

        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (type.equals("P")) {
            receiver = Server.getProfessors().get(Integer.valueOf(userName.getText()));
        }else {
            receiver = Server.getStudents().get(Integer.valueOf(userName.getText()));
        }
    }
    private void sendActionPerformed(java.awt.event.ActionEvent evt) {
        for (String s : receiver.getMessages().keySet()){
            if (s.equals(sender.getName())){
                receiver.getMessages().remove(s);
            }
        }
        receiver.getMessages().put(sender.getName(),messageToSend.getText());
        messages.setText(messages.getText()+"Me : "+messageToSend.getText()+"\n");
    }

    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton Professor;
    private javax.swing.JLabel error;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField messageToSend;
    private javax.swing.JTextArea messages;
    private javax.swing.JLabel receiverName;
    private javax.swing.JButton send;
    private javax.swing.JRadioButton student;
    private javax.swing.JTextArea userList;
    private javax.swing.JTextField userName;
    private String type;
    private User sender;
    private User receiver;

    @Override
    public void run() {

        for(String s : sender.getMessages().keySet()){
            if (s.equals(receiver.getName())){
                messages.setText(messages.getText()+sender.getMessages().get(s)+"\n");
            }
        }
    }
    // End of variables declaration                   
}
