package Frame.Student;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 1
 */
public class choosingCourse extends javax.swing.JFrame {

    /**
     * Creates new form choosingCourse
     */
    public choosingCourse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        recomended = new javax.swing.JButton();
        college = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        courses = new javax.swing.JTextArea();
        collegeName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        courseNumT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        grade = new javax.swing.JRadioButton();
        Units = new javax.swing.JRadioButton();
        Alphabetic = new javax.swing.JRadioButton();
        markingT = new javax.swing.JCheckBox();
        takeCourse = new javax.swing.JButton();
        takeDeputy = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        takenCourses = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        courseNum1 = new javax.swing.JTextField();
        marking1 = new javax.swing.JCheckBox();
        changeGroup = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        eror = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setLayout(null);

        recomended.setBackground(new java.awt.Color(204, 204, 204));
        recomended.setText("Recomended");
        jPanel1.add(recomended);
        recomended.setBounds(120, 270, 100, 22);

        college.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(college);
        college.setBounds(200, 300, 20, 20);

        courses.setBackground(new java.awt.Color(255, 255, 204));
        courses.setColumns(20);
        courses.setRows(5);
        jScrollPane1.setViewportView(courses);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(260, 180, 240, 200);

        collegeName.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(collegeName);
        collegeName.setBounds(120, 300, 71, 22);

        jLabel1.setText("Enter college name :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 300, 110, 20);
        jPanel1.add(courseNumT);
        courseNumT.setBounds(220, 80, 110, 22);

        jLabel2.setText("Course number : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 80, 130, 20);

        grade.setText("Grade");
        grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeActionPerformed(evt);
            }
        });
        jPanel1.add(grade);
        grade.setBounds(510, 210, 54, 20);

        Units.setText("Units");
        Units.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnitsActionPerformed(evt);
            }
        });
        jPanel1.add(Units);
        Units.setBounds(510, 240, 50, 20);

        Alphabetic.setText("Alphabetic");
        Alphabetic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlphabeticActionPerformed(evt);
            }
        });
        jPanel1.add(Alphabetic);
        Alphabetic.setBounds(510, 270, 80, 20);

        markingT.setText("Mark it");
        markingT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markingTActionPerformed(evt);
            }
        });
        jPanel1.add(markingT);
        markingT.setBounds(340, 80, 60, 20);

        takeCourse.setBackground(new java.awt.Color(204, 204, 204));
        takeCourse.setText("Take it");
        takeCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeCourseActionPerformed(evt);
            }
        });
        jPanel1.add(takeCourse);
        takeCourse.setBounds(380, 430, 120, 22);

        takeDeputy.setBackground(new java.awt.Color(204, 204, 204));
        takeDeputy.setText("Take it (Deputy)");
        takeDeputy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeDeputyActionPerformed(evt);
            }
        });
        jPanel1.add(takeDeputy);
        takeDeputy.setBounds(380, 460, 120, 22);

        takenCourses.setBackground(new java.awt.Color(255, 255, 204));
        takenCourses.setColumns(20);
        takenCourses.setRows(5);
        jScrollPane2.setViewportView(takenCourses);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 80, 100, 160);

        jLabel3.setText("Course number : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 400, 130, 20);
        jPanel1.add(courseNum1);
        courseNum1.setBounds(260, 400, 110, 22);

        marking1.setText("Mark it");
        marking1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marking1ActionPerformed(evt);
            }
        });
        jPanel1.add(marking1);
        marking1.setBounds(380, 400, 60, 20);

        changeGroup.setBackground(new java.awt.Color(204, 204, 204));
        changeGroup.setText("Change Group");
        changeGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeGroupActionPerformed(evt);
            }
        });
        jPanel1.add(changeGroup);
        changeGroup.setBounds(340, 110, 120, 22);

        Delete.setBackground(new java.awt.Color(204, 204, 204));
        Delete.setText("Delete");
        jPanel1.add(Delete);
        Delete.setBounds(340, 140, 120, 22);
        jPanel1.add(eror);
        eror.setBounds(110, 500, 370, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void AlphabeticActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void UnitsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void gradeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void markingTActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void takeCourseActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void takeDeputyActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void marking1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void changeGroupActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(choosingCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(choosingCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(choosingCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(choosingCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new choosingCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JRadioButton Alphabetic;
    private javax.swing.JButton Delete;
    private javax.swing.JRadioButton Units;
    private javax.swing.JButton changeGroup;
    private javax.swing.JButton college;
    private javax.swing.JTextField collegeName;
    private javax.swing.JTextField courseNum1;
    private javax.swing.JTextField courseNumT;
    private javax.swing.JTextArea courses;
    private javax.swing.JLabel eror;
    private javax.swing.JRadioButton grade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox marking1;
    private javax.swing.JCheckBox markingT;
    private javax.swing.JButton recomended;
    private javax.swing.JButton takeCourse;
    private javax.swing.JButton takeDeputy;
    private javax.swing.JTextArea takenCourses;
    // End of variables declaration
}
