package Frame.Student;

    /*
     * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
     * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
     */

import Logic.Deputy;
import Logic.Student;
import Server.Server;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
     *
     * @author 1
     */
    public class mainStudent extends javax.swing.JFrame {

        /**
         * Creates new form mainStudent
         */
        public mainStudent(Student student) {
            this.student = student;
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

            jPanel1 = new javax.swing.JPanel();
            jButton1 = new javax.swing.JButton();
            jButton2 = new javax.swing.JButton();
            jButton3 = new javax.swing.JButton();
            jButton4 = new javax.swing.JButton();
            eduAdmin = new javax.swing.JButton();
            messenger = new javax.swing.JButton();
            message = new javax.swing.JButton();
            jLabel1 = new javax.swing.JLabel();
            picture = new javax.swing.JLabel();
            lastEntry = new javax.swing.JLabel();
            Time = new javax.swing.JLabel();
            Date = new javax.swing.JLabel();
            jButton5 = new javax.swing.JButton();
            jButton55 = new javax.swing.JButton();
            jButton66 = new javax.swing.JButton();
            jButton77 = new javax.swing.JButton();
            jButton88 = new javax.swing.JButton();
            jButton99 = new javax.swing.JButton();
            choosing = new javax.swing.JButton();
            studyStatus = new javax.swing.JLabel();
            guidingP = new javax.swing.JLabel();
            SingnupCertification = new javax.swing.JLabel();
            signupTime = new javax.swing.JLabel();
            email = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            choosing.setVisible(false);
            jPanel1.setLayout(null);
            for (Deputy d : Server.getDeputies()){
                if (d.getCollege().equals(student.getCollege())){
                    for (Integer i: d.getTimeToChoose().keySet()){
                        if (i==student.getYearOfEntry()){
                            if (d.getTimeToChoose().get(i).equals(date)){
                                choosing.setVisible(true);
                            }
                        }
                    }
                }
            }

            jButton1.setBackground(new java.awt.Color(204, 204, 204));
            jButton1.setText("Educational Service");
            jPanel1.add(jButton1);
            jButton1.setBounds(20, 170, 160, 22);

            jButton2.setBackground(new java.awt.Color(204, 204, 204));
            jButton2.setText("Grades");
            jPanel1.add(jButton2);
            jButton2.setBounds(20, 220, 160, 22);

            jButton3.setBackground(new java.awt.Color(204, 204, 204));
            jButton3.setText("User Profile");
            jPanel1.add(jButton3);
            jButton3.setBounds(20, 270, 160, 22);

            jButton4.setBackground(new java.awt.Color(204, 204, 204));
            jButton4.setText("Signup Matters");
            jPanel1.add(jButton4);
            jButton4.setBounds(20, 120, 160, 22);

            choosing.setBackground(new java.awt.Color(204, 204, 204));
            choosing.setText("Choosing units");
            jPanel1.add(choosing);
            choosing.setBounds(20, 320, 160, 22);

            jLabel1.setFont(new java.awt.Font("Segoe UI Light", 3, 24)); // NOI18N
            jLabel1.setText("EDU SHARIF");
            jPanel1.add(jLabel1);
            jLabel1.setBounds(30, 0, 140, 40);
            jPanel1.add(picture);
            picture.setBounds(70, 50, 40, 60);
            jPanel1.add(lastEntry);
            lastEntry.setBounds(370, 60, 210, 30);
            jPanel1.add(Time);
            Time.setBounds(370, 100, 200, 30);
            jPanel1.add(Date);
            Date.setBounds(370, 140, 200, 30);
            times();
            dt();
            email.setText("Email : "+student.getEmail());
            guidingP.setText("Guiding professor : "+student.getGuidingP());
            studyStatus.setText("Study status : "+ student.getStatus());
            signupTime.setText("Signup Date : "+student.getSignupDate());

            jButton5.setBackground(new java.awt.Color(204, 204, 204));
            jButton5.setText("Exit");
            jPanel1.add(jButton5);
            jButton5.setBounds(520, 470, 72, 22);

            message.setIcon(new ImageIcon("D:/finalEDU/src/Images/bell.png"));
            jPanel1.add(message);
            message.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    messageActionPerformed(evt);
                }
            });
            message.setBounds(408, 470, 21, 22);

            messenger.setIcon(new ImageIcon("D:/finalEDU/src/Images/messageIcon.png"));
            jPanel1.add(messenger);
            messenger.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    messengerActionPerformed(evt);
                }
            });
            messenger.setBounds(429, 470, 21, 22);

            eduAdmin.setText("Admin");
            jPanel1.add(eduAdmin);
            eduAdmin.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    eduAdminActionPerformed(evt);
                }
            });
            eduAdmin.setBounds(450, 470, 76, 22);

            jPanel1.add(studyStatus);
            studyStatus.setBounds(210, 170, 180, 0);
            jPanel1.add(guidingP);
            guidingP.setBounds(210, 220, 380, 20);
            jPanel1.add(SingnupCertification);
            SingnupCertification.setBounds(210, 270, 360, 20);
            jPanel1.add(signupTime);
            signupTime.setBounds(210, 310, 360, 0);
            jPanel1.add(email);
            email.setBounds(0, 460, 310, 40);

            jButton55.setBackground(new java.awt.Color(255, 179, 200));
            jButton55.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton55ActionPerformed(evt);
                }
            });
            jPanel1.add(jButton55);
            jButton55.setBounds(490, 20, 20, 20);

            jButton66.setBackground(new java.awt.Color(153, 232, 173));
            jButton66.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton66ActionPerformed(evt);
                }
            });
            jPanel1.add(jButton66);
            jButton66.setBounds(460, 20, 20, 20);

            jButton77.setBackground(new java.awt.Color(149, 126, 184));
            jButton77.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton77ActionPerformed(evt);
                }
            });
            jPanel1.add(jButton77);
            jButton77.setBounds(430, 20, 20, 20);

            jButton88.setBackground(new java.awt.Color(237, 197, 28));
            jButton88.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton88ActionPerformed(evt);
                }
            });
            jPanel1.add(jButton88);
            jButton88.setBounds(400, 20, 20, 20);

            jButton99.setBackground(new java.awt.Color(255, 148, 144));
            jButton99.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton99ActionPerformed(evt);
                }
            });
            jPanel1.add(jButton99);
            jButton99.setBounds(520, 20, 20, 20);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            );

            pack();
        }
    private void jButton88ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(237,197,28));
    }
    private void choosingActionPerformed(java.awt.event.ActionEvent evt) {

    }
    private void jButton77ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(149,126,184));
    }

    private void jButton66ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(153,232,173));
    }

    private void messageActionPerformed(java.awt.event.ActionEvent evt) {

    }
    private void messengerActionPerformed(java.awt.event.ActionEvent evt) {

    }
    private void eduAdminActionPerformed(java.awt.event.ActionEvent evt) {

    }



    private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(255,179,200));
    }

    private void jButton99ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.setBackground(new Color(255,148,144));
    }
        // </editor-fold>

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(mainStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(mainStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(mainStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(mainStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new mainStudent(new Student()).setVisible(true);
                }
            });
        }

        // Variables declaration - do not modify
        private javax.swing.JLabel SingnupCertification;
        private javax.swing.JLabel Time;
        private javax.swing.JLabel email;
        private String date;
        private javax.swing.JLabel guidingP;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JButton jButton5;
    private javax.swing.JButton choosing;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton99;
    private javax.swing.JButton eduAdmin;
    private javax.swing.JButton messenger;
    private javax.swing.JButton message;

        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel Date;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel lastEntry;
        private javax.swing.JLabel picture;
        private javax.swing.JLabel signupTime;
        private javax.swing.JLabel studyStatus;
        private Student student;
        // End of variables declaration

    public void dt(){
        Date d  =new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MMM-dd");
        String dd = sdf.format(d);
        Date.setText(dd);
        date = dd;
    }
    // time
    Timer t ;
    SimpleDateFormat st ;
    public void times(){

        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                Date dt  =new Date();
                st = new SimpleDateFormat("hh:mm:ss");
                String tt = st.format(dt);
                Time.setText(tt);
            }
        });
        t.start();

    }

}


